In [1]:
import pandas as pd
import numpy as np
from fancyimpute import KNN

In [2]:
test = pd.read_csv('cs-test.csv')
train = pd.read_csv('cs-training.csv')
print test.shape
print train.shape

(101503, 12)
(150000, 12)


In [3]:
print train.columns

Index([u'Unnamed: 0', u'SeriousDlqin2yrs',
       u'RevolvingUtilizationOfUnsecuredLines', u'age',
       u'NumberOfTime30-59DaysPastDueNotWorse', u'DebtRatio', u'MonthlyIncome',
       u'NumberOfOpenCreditLinesAndLoans', u'NumberOfTimes90DaysLate',
       u'NumberRealEstateLoansOrLines',
       u'NumberOfTime60-89DaysPastDueNotWorse', u'NumberOfDependents'],
      dtype='object')


In [4]:
train = train.drop('Unnamed: 0', axis=1)

In [7]:
# KNN imputation
tmp = train.select_dtypes(include=[np.float]).head(n=100).as_matrix()
tmpFilled = pd.DataFrame(KNN(k=3).complete(tmp))

Imputing row 1/100 with 0 missing, elapsed time: 0.008


In [16]:
print tmpFilled.shape
print tmp.shape
print train.select_dtypes(include=[np.float]).columns

(100, 4)
(100, 4)
Index([u'RevolvingUtilizationOfUnsecuredLines', u'DebtRatio', u'MonthlyIncome',
       u'NumberOfDependents'],
      dtype='object')


In [13]:
print tmp

[[  7.66126609e-01   8.02982129e-01   9.12000000e+03   2.00000000e+00]
 [  9.57151019e-01   1.21876201e-01   2.60000000e+03   1.00000000e+00]
 [  6.58180140e-01   8.51133750e-02   3.04200000e+03   0.00000000e+00]
 [  2.33809776e-01   3.60496820e-02   3.30000000e+03   0.00000000e+00]
 [  9.07239400e-01   2.49256950e-02   6.35880000e+04   0.00000000e+00]
 [  2.13178682e-01   3.75606969e-01   3.50000000e+03   1.00000000e+00]
 [  3.05682465e-01   5.71000000e+03              nan   0.00000000e+00]
 [  7.54463648e-01   2.09940017e-01   3.50000000e+03   0.00000000e+00]
 [  1.16950644e-01   4.60000000e+01              nan              nan]
 [  1.89169052e-01   6.06290901e-01   2.36840000e+04   2.00000000e+00]
 [  6.44225962e-01   3.09476210e-01   2.50000000e+03   0.00000000e+00]
 [  1.87981200e-02   5.31528760e-01   6.50100000e+03   2.00000000e+00]
 [  1.03518570e-02   2.98354075e-01   1.24540000e+04   2.00000000e+00]
 [  9.64672555e-01   3.82964747e-01   1.37000000e+04   2.00000000e+00]
 [  1.

In [18]:
from IPython.display import display
display(tmpFilled)

0             1             2        3
0   0.766127      0.802982   9120.000000  2.00000
1   0.957151      0.121876   2600.000000  1.00000
2   0.658180      0.085113   3042.000000  0.00000
3   0.233810      0.036050   3300.000000  0.00000
4   0.907239      0.024926  63588.000000  0.00000
5   0.213179      0.375607   3500.000000  1.00000
6   0.305682   5710.000000      0.170694  0.00000
7   0.754464      0.209940   3500.000000  0.00000
8   0.116951     46.000000   6049.642416  0.94580
9   0.189169      0.606291  23684.000000  2.00000
10  0.644226      0.309476   2500.000000  0.00000
11  0.018798      0.531529   6501.000000  2.00000
12  0.010352      0.298354  12454.000000  2.00000
13  0.964673      0.382965  13700.000000  2.00000
14  0.019657    477.000000      0.000000  0.00000
15  0.548458      0.209892  11362.000000  2.00000
16  0.061086   2058.000000      0.806273  0.00000
17  0.166284      0.188274   8800.000000  0.00000
18  0.221813      0.527888   3280.000000  2.00000
19  0.602794      0.065868    333.000000  0.00000
20  0.200923      0.430046  12300.000000  0.00000
21  0.025656      0.475841   3000.000000  2.00000
22  1.000000      0.241104   2500.000000  0.00000
23  0.075427      0.085512   7916.000000  0.00000
24  0.046560      0.241622   2416.000000  0.00000
25  0.392248      1.595253   4676.000000  1.00000
26  0.052436      0.097672   8333.000000  0.00000
27  0.034421      0.042383   2500.000000  1.00000
28  0.452516      0.011761   3400.000000  0.00000
29  0.392995      0.436103   5500.000000  0.00000
..       ...           ...           ...      ...
70  0.265898      0.262612   8384.000000  1.00000
71  0.142013   1824.000000      0.978530  0.00000
72  0.827708      0.369591   6793.000000  0.00000
73  0.059669   3162.000000      0.000000  1.00000
74  0.133063      0.182882  10257.000000  3.00000
75  0.234218      0.116614   8600.000000  3.00000
76  0.122296      0.694647   4800.000000  0.00000
77  0.460376      0.074156   4975.000000  0.00000
78  0.335559      0.270449  15000.000000  1.00000
79  0.270523      2.797699   1042.000000  2.00000
80  0.183317      0.111132  10833.000000  1.00000
81  0.074862      0.208842   4500.000000  0.00000
82  0.017259      2.604511  12414.000000  2.00000
83  0.054497      0.492022   4950.000000  0.00000
84  0.029164      0.395032   3300.000000  0.00000
85  0.000000      0.316145   4886.000000  1.00000
86  0.360510   3282.000000      0.003996  0.00000
87  0.003750      0.004061   3200.000000  0.00000
88  0.734478      0.591478   4716.000000  2.00000
89  0.080564      0.487289   4916.000000  0.00000
90  0.039388  15466.000000      0.000000  0.00000
91  0.023767      0.123798  10500.000000  0.00000
92  0.784836   2662.000000      0.101382  0.00000
93  0.888822      0.368404   3050.000000  1.00000
94  0.791174      0.512415   3100.000000  0.00000
95  0.245353      0.288417   6500.000000  0.00000
96  0.542243     10.000000   6048.527083  1.72571
97  0.010531      0.280665   5714.000000  0.00000
98  0.363200      0.480524   2900.000000  0.00000
99  0.032618      0.006799   7500.000000  0.00000

[100 rows x 4 columns]