# Numpy学习笔记

## Numpy简介



## 1. ndarray多维数据对象
ndarray是一个通用的同构数据多维容器，也就是说里面的元素必需是相同类型。ndarray都有一个`shape`和`dtype`属性，用于指明数组的维度和数据中的数据类型。N维数据对象ndarray在数据分析中经常用到，熟悉掌握它能够方便我们进行数据分析。
### 1.1 数组创建

In [2]:
import numpy as np

# 按照正态分布（0，1）生成10个随机数
data = np.array(np.random.normal(0,1,10))

# 还可以这么创建，会自动推断dtype类型
data1 = [[1,2,3,4], [5,6,7,8]]
arry1 = np.array(data1) 
print arry1.dtype
# 将上面的一维数据转换成2 X 5 的array，可以试试data.shape=(3.3)有什么结果
data.shape = (2,5)

int64


In [26]:
print data * 10
print data
print data.shape
print data.dtype

[[ -0.19616902   2.49520245  -6.14555902  -9.04647232 -17.88230055]
 [  7.40377203   0.41996745   4.68369247  -3.58210019 -17.61736922]]
[[-0.0196169   0.24952025 -0.6145559  -0.90464723 -1.78823005]
 [ 0.7403772   0.04199674  0.46836925 -0.35821002 -1.76173692]]
(2, 5)
float64


In [9]:
# 创建一个全是0的数组
np.zeros(10)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
# 创建一个全是1的数组
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [8]:
# 创建一个空的数组，因为返回全0的数组是不安全的，所以会自动添加上值
np.empty((2,3))

array([[  1.21802121e-312,   1.70335574e-316,   6.90383046e-310],
       [  6.90384679e-310,   6.90384371e-310,   6.90383047e-310]])

In [10]:
# range函数创建
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

其他创建数组的方法：
+ **asarray**：将输入转换为ndarray，如果输入是ndarray就不进行  
+ **zeros_like**：根据输入数组的形状创建一个全是0的数组
+ **ones_like**：根据输入数组的形状创建一个全是1的数组
+ **empty_like**：根据输入数组形状创建一个空数组
+ **eye**，**identity**：创建一个单位矩阵

In [11]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [12]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 1.2 数组类型
**dtype**是一种特殊的对象，含有ndarray将一块内存解释为特定数据类型的所需信息，方便将不同数据类型映射到计算机能识别的表示。数据型dytpe的命名格式相同：一个类型名（int，float），后面跟一个用于表示各元素位长的数字。标准双精度浮点数需要占用8个字节，所以用float64表示。

In [13]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([3,4,5], dtype=np.int32)
print arr1.dtype
print arr2.dtype

float64
int32


|Data type | Type code | Description| 
| -- | -- | -- |
|bool_ | ? | 	Boolean (True or False) stored as a byte |
|int_ |  | 	Default integer type (same as C long; normally either int64 or int32) |
|intc |  | 	Identical to C int (normally int32 or int64) |
|intp |  | 	Integer used for indexing (same as C ssize_t; normally either int32 or int64) |
|int8 | i1 |	一个字节，Byte (-128 to 127)|
|int16 | i2 |	Integer (-32768 to 32767)|
|int32 | i4 |	Integer (-2147483648 to 2147483647)|
|int64 | i8 |	Integer (-9223372036854775808 to 9223372036854775807)|
|uint8 | u1 |	Unsigned integer (0 to 255)|
|uint16 | u2 |	Unsigned integer (0 to 65535)|
|uint32 | u4 |	Unsigned integer (0 to 4294967295)|
|uint64 | u8 |	Unsigned integer (0 to 18446744073709551615)|
|float_ |  |	Shorthand for float64.|
|float16 | f2 |	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa|
|float32 | f4或f |	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa|
|float64 | f8或d |	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa|
|complex_ | |	Shorthand for complex128.|
|complex64 | c8 |	Complex number, represented by two 32-bit floats (real and imaginary components)|
|complex128 | c16 |	Complex number, represented by two 64-bit floats (real and imaginary components)| 
| object | O | python object 对象 |
| string_ | S | 固定长度的字符串类型（每个字符一个字节），10个长度的字符串，应为S10 |
| unicode_ | U | 固定长度的unicode类型，和字符串类似 |

In [16]:
# 利用type code缩写来设置数组类型
np.array([1,2,3,4,5], dtype='i1')

array([1, 2, 3, 4, 5], dtype=int8)

In [18]:
# astype不同类型间的转换,该方法会创建一个新的数组
str1 = np.array(['1', '2','3','4'], dtype=np.string_)
print str1
str1.astype('i1')

['1' '2' '3' '4']


array([1, 2, 3, 4], dtype=int8)

### 1.3 数组与标题之间的运算
数组可以不用循环就可以方便地对数据进行指计算，这个特性称为矢量化（vectorization），R语言中的**vector**,**data.frame**也支持这个特性。大小相同的两个数组之间的任何运算都会就到到元素级别。

In [9]:
arry1 = np.arange(6)
arry1.shape = (2,3)
arry2 = np.arange(10,16)
arry2.shape = (2,3)
print arry1
print arry2

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]


In [10]:
arry1 * arry2 

array([[ 0, 11, 24],
       [39, 56, 75]])

In [11]:
arry1 + arry2 

array([[10, 12, 14],
       [16, 18, 20]])

In [13]:
# 与标量的运算
7 + arry1

array([[ 7,  8,  9],
       [10, 11, 12]])

不同大小数组之间的运算称为广播（broadcasting），计算过程比较上面复杂。

### 1.4 切片与索引
和Python中的**list**一样，数组也可以进行切片与索引，从中选取部分数据。

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5:8]

array([5, 6, 7])

In [25]:
arr[5:8] = 15
print arr
x = arr[5:8]
print x
x[1] = 12345
print x
print arr
# 查看这两个地方引用的内存地址是否一样
print id(x[1])
print id(arr[6])

[ 0  1  2  3  4 15 15 15  8  9]
[15 15 15]
[   15 12345    15]
[    0     1     2     3     4    15 12345    15     8     9]
140544018689912
140544018689912


最后一个例子可以发现，数组对象和Python的列表对象一样，是可变的。不过有一种很重要的不一样是，当我们改变**x**中的值时，**arr**中的值也发生变化了（从15变为12345）。就明在切片的时候，数据不会复制，任何修改都会反映到原始数组上，因为它们引用的内存地址是一样的。设计成这样的原因大概是因为Numpy在用于处理大数据时，如果复制一个数据，可能会造成很大的内存开销。如果想要进行复制，可以利用`np.array.copy()`方法进行复制，可以把该值复制到新的变量上，而不影响原始数组。

In [26]:
arr2d = np.arange(9)
arr2d.shape = (3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
# 这两种索引方法结果一样
print arr2d[1][2]
print arr2d[1,2]

5
5


In [29]:
arr3d = np.arange(27)
arr3d.shape = (3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
print arr3d[1].shape
arr3d[1]

(3, 3)


array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [31]:
arr3d[1,1,2]

14

In [32]:
arr3d[1][1][2]

14

In [33]:
# 等于arr3d[:,2],得到一个二维数组
arr3d[:][2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])